Print error when download of font file fails
Sometimes downloads from Google's servers fail. Since we invoked the
actual download without curl's -S flag, no error message would have been
printed and the script just exits.

Improve the user experience in this case by capturing the error string
and showing it to the user. If an error occurs, downloading will
continue with the next font type, but a non-zero exit code will be
returned anyway.

Closes: #17

diff --git a/google-font-download b/google-font-download
--- a/google-font-download
+++ b/google-font-download
@@ -448,7 +448,13 @@ for family in "${families[@]}"; do
 			svgname=$(echo "$file" | $ESED 's/^[^#]+#(.*)$/\1/g')
 		fi
 		# Actually download the font file
-		curl -sfL "$file" -o "${fontnameescaped}.$uakey"
+		ret=0
+		download_error=$(curl -sSfL "$file" -o "${fontnameescaped}.$uakey" 2>&1) || ret=$?
+		if [ $ret -ne 0 ]; then
+			errors=1
+			printf >&2 "\nerror downloading %s: %s\n" "${uakey}" "${download_error}"
+			continue
+		fi
 
 		# Generate the CSS statements required to include the downloaded file.
 		case "$uakey" in
